#!/usr/bin/python3
def error_mail(error_, mail_to, mail_from, mail_pass):
    import smtplib, ssl
    port = 465  # For SSL
    smtp_server = "smtp.gmail.com"
    sender_email = mail_from
    receiver_email = mail_to
    password = mail_pass
    message = f"""\
    Subject: LFD auto email Error
    {error_msg}\n\n{error_}"""
    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, message)