#!/usr/bin/python3
import sys
subject = ' '.join(
    sys.argv[1:])

import smtplib
from email.mime.text import MIMEText
MAIL_FROM = "amir.saleem@lovefordata.com"
MAIL_HOST = "smtp.gmail.com"
MAIL_PORT = "587"
MAIL_USER = "amir.saleem@lovefordata.com"
MAIL_PASS =  open(".pass", "r").read().strip()

def send_email(email_html, start_time):
    message = MIMEText(email_html, 'html')
    message['From'] = MAIL_FROM
    for MAIL_CUSTOMER in ["amir.saleem@lovefordata.com", "daniyal.faquih@lovefordata.com"]: 
        message = 'Subject: {}\n\n{}'.format("Kashat ETL error (Testing) " + str(start_time.strftime('%d-%m-%Y')), subject)
        server = smtplib.SMTP('{0}:{1}'.format(MAIL_HOST, MAIL_PORT))
        server.starttls()
        server.login(MAIL_USER, MAIL_PASS)
        server.sendmail(MAIL_FROM, MAIL_CUSTOMER, message)
        server.quit()
import datetime
send_email("Kashat ETL error", datetime.datetime.now())
